name: Linting Testing Building
on:
  push:
  pull_request:
   branches:
    - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16.x

    steps:
     - uses: actions/checkout@v2
     - name: Install Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
        node-version: ${{ matrix.node-version }}
     - name: Install application dependencies
       run: npm install
     - name: Run eslint checking ...
       run: npm run lint:ts
     - name: Run stylelint checking ...
       run: npm run lint:scss
     - name: Run unit tests
       run: npm run test:unit
     - name: Run screenshot tests...
       run: npm run storybook:build && loki --requireReference --reactUri file:./storybook-static
     - name: Generate application build
       run: npm run build:prod