name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
  pull_request:
   branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
         node-version: 16.3.1
      - name: Install application dependencies
        run: npm install
      - name: Run unit tests
        run: npm test:unit
      - name: Run eslint checking ...
        run: npm lint:ts
      - name: Run stylelint checking ...
        run: npm lint:ts
      - name: Generate application build
        run: npm run build