name: Linting Testing Building
on:
  push:
  pull_request:
   branches:
    - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
     matrix:
      node-version: [ 16.x ]

    steps:
     - uses: actions/checkout@v2
     - name: Install Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
        node-version: ${{ matrix.node-version }}
     - name: Install application dependencies
       run: npm ci --force
     - name: Run eslint checking ...
       run: npm run lint:ts
       if: always()
     - name: Run stylelint checking ...
       run: npm run lint:scss
       if: always()
     - name: Run unit tests
       run: npm run test:unit
       if: always()
     - name: Run screenshot tests 1 step "build storybook"
       run: npm run storybook:build
     - name: Run screenshot tests 2 step "screenshot test"
       run: npm run test:ui:ci
     - name: Generate application build
       run: npm run build:prod